name: Automated deployment

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run prettier check
        run: npm run check

  build-container:
    needs: quality-check
    runs-on: ubuntu-latest
    env:
      # TAG_DYNAMIC: main-1234567
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}
      IMAGE_NAME: angular-todos-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag $IMAGE_NAME:$TAG_DYNAMIC \
          --tag $IMAGE_NAME:latest

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to docker hub
        run: |
          docker push $IMAGE_NAME:$TAG_DYNAMIC
          docker push $IMAGE_NAME:latest
