name: Automated deployment

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run prettier check
        run: npm run check

  build-container:
    needs: quality-check
    runs-on: ubuntu-latest
    env:
      # TAG_DYNAMIC: main-1234567
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag angular-todos-app:$TAG_DYNAMIC \
          --tag angular-todos-app:latest

      # - name: wohin docker image
